{"version":1,"resource":"vscode-remote://wsl%2Bubuntu/home/kraoshin/holbertonschool-higher_level_programming/python-exceptions/5-raise_exception.py","entries":[{"id":"uTtt.py","timestamp":1737544326703}]}